name: SentienceEntity
version: '1.9.1'
main: de.t0bx.sentienceEntity.SentienceEntity
api-version: '1.21'
authors: [ t0bx ]
commands:
  se:
    permission: se.command
    aliases:
      - sentienceentity